language: perl
sudo: false
perl:
# - "5.12"
# - "5.14"
# - "5.16"
# - "5.18"
# - "5.20"
  - "5.22"
# - "5.24"
# - "5.26"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get remove libssl0.9.8
  - sudo apt-get install -y libffi6 libffi-dev libssl1.0.0 software-properties-common
  - find / -name 'libcrypto*' 2>/dev/null || echo "File not found"
#  - sudo strings /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 | grep PEM_read_bio
#  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
#  - sudo apt-get update
#  - sudo apt-get install -y libssl1.0.0
#  - sudo dpkg -L libssl1.0.0
#  - sudo dpkg -l
